### ISSUE TITLE
`ReadPackage` should return default parameter values that aren't variables or structs

### ISSUE THREAD

**Issue by mieubrisse** [kurtosis-tech/kurtosis-package-indexer#50]
In cases where the default parameter values are primitives (e.g. `my_param=False`), we should return the value via `ReadPackage` so the frontend can do stuff with it.

NOTE: we CANNOT parse non-primitive values because something like `my_param=MY_CONSTANT` would require interpreting the Starlark.

**Comment by tedim52** [comment]
Addressed by: https://github.com/kurtosis-tech/kurtosis-package-indexer/pull/54
