### ISSUE TITLE
Track and return the 'number of uses' of a kurtosis package

### ISSUE THREAD

**Issue by Dartoxian** [kurtosis-tech/kurtosis-package-indexer#62]
Our designs specify a 'uses' count value. This value is not currently returned when a package is read from the indexer.

![image](https://github.com/kurtosis-tech/kurtosis-package-indexer/assets/4419574/b78a8ea0-ec54-4f51-891a-9b8c00db3c83)

I'm not sure exactly what this value should be, but presumably we need something like:
* a `recordUsage` endpoint which counts the use of a kurtosis package (this endpoint would be pinged in the run starlark code).
* the `kurtosisPackage` object should have a `usageCount` property.

Perhaps the usage of a package is already tracked somewhere in a metrics server - please point me to it if that's the case.

**Comment by leoporoli** [comment]
it was implemented here: https://github.com/kurtosis-tech/kurtosis-package-indexer/pull/74

**Comment by leoporoli** [comment]
it was implemented here: https://github.com/kurtosis-tech/kurtosis-package-indexer/pull/74
